.PHONY: dev copy-types

copy-types: ./api/src/chat/types.ts
	@echo "Copying types to client"
	@echo "// this file is generated by make copy-types\n\n$$(cat ./api/src/chat/types.ts)" > ./site/src/protocol/types.ts

dev:
	@echo "Starting development server"
	@./runner.sh
	

	